import type { NextPage, GetStaticPaths, GetStaticProps } from 'next'
import Head from 'next/head'

const Country: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Country Name</h1>
      </main>
    </div>
  )
}

export default Country

// export const getStaticPaths: GetStaticPaths = async () => {
// }

// export const getStaticProps: GetStaticProps = async () => {
// }