import type { NextPage, GetStaticPaths, GetStaticProps } from 'next'
import Head from 'next/head'
import { Country } from '../types'

const Country: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Country Name</h1>
      </main>
    </div>
  )
}

export default Country

export const getStaticPaths: GetStaticPaths = async () => {
  const res = await fetch('https://restcountries.com/v3.1/all')
  const data = await res.json()
  const paths = data.map((country: Country) => ({ params: { country: country.name.common } }));

  return {
    paths,
    fallback: "blocking",
  }
}

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const res = await fetch(`https://restcountries.com/v3.1/name/${params?.country}?fullText=true`)
  const data = await res.json()
  const country = data[0]

  return {
    props: {
      country
    }
  }

}